[package]
name = "bevy_egui_web_showcase"
version = "0.2.0"
authors = ["mvlabat <mvlabat@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", default-features = false, features = ["x11", "bevy_winit", "render"] }
bevy_egui = "0.4.0"
bevy_webgl2 = "0.5.0"
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2.69"

[patch.crates-io]
#bevy_egui = { path = "../bevy_egui" }
#bevy_webgl2 = { git = "https://github.com/mvlabat/bevy_webgl2.git", branch = "fix-scissor-test" }
